apiVersion: v1
kind: ServiceAccount
metadata:
  name: sandbox
  namespace: tetral-system
  labels:
    app.kubernetes.io/name: sandbox
    app.kubernetes.io/part-of: tetral
automountServiceAccountToken: false
