apiVersion: v1
kind: ServiceAccount
metadata:
  name: provider-gateway
  namespace: tetral-system
  labels:
    app.kubernetes.io/name: provider-gateway
    app.kubernetes.io/part-of: tetral
automountServiceAccountToken: false
