apiVersion: v1
kind: ConfigMap
metadata:
  name: bridge-config
  namespace: tetral-system
  labels:
    app.kubernetes.io/name: bridge
    app.kubernetes.io/part-of: tetral
data:
  TETRAL_PROVIDER_RESCHEDULE_BUDGET: "3"
  TETRAL_COMPACTION_RESCHEDULE_BUDGET: "2"
