apiVersion: v1
kind: ServiceAccount
metadata:
  name: bridge
  namespace: tetral-system
  labels:
    app.kubernetes.io/name: bridge
    app.kubernetes.io/part-of: tetral
automountServiceAccountToken: false
