apiVersion: v1
kind: ServiceAccount
metadata:
  name: git-proxy
  namespace: tetral-system
  labels:
    app.kubernetes.io/name: git-proxy
    app.kubernetes.io/part-of: tetral
automountServiceAccountToken: false
