apiVersion: v1
kind: Service
metadata:
  name: event-stream
  namespace: tetral-system
  labels:
    app.kubernetes.io/name: event-stream
    app.kubernetes.io/component: event-stream
    app.kubernetes.io/part-of: tetral
    app.kubernetes.io/managed-by: kustomize
    tetral.ai/exposure: public
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: event-stream
  ports:
    - name: http
      port: 8080
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: event-stream-metrics
  namespace: tetral-system
  labels:
    app.kubernetes.io/name: event-stream
    app.kubernetes.io/component: event-stream
    app.kubernetes.io/part-of: tetral
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: event-stream
  ports:
    - name: metrics
      port: 8081
      targetPort: metrics
