apiVersion: v1
kind: ServiceAccount
metadata:
  name: event-stream
  namespace: tetral-system
  labels:
    app.kubernetes.io/name: event-stream
    app.kubernetes.io/component: event-stream
    app.kubernetes.io/part-of: tetral
    app.kubernetes.io/managed-by: kustomize
automountServiceAccountToken: false
