apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-runner
  namespace: tetral-system
  labels:
    app.kubernetes.io/name: job-runner
    app.kubernetes.io/part-of: tetral
automountServiceAccountToken: false
