apiVersion: v1
kind: ServiceAccount
metadata:
  name: queue
  namespace: tetral-system
  labels:
    app.kubernetes.io/name: queue
    app.kubernetes.io/part-of: tetral
automountServiceAccountToken: false
