apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cleanup
  namespace: tetral-system
  labels:
    app.kubernetes.io/name: cleanup
    app.kubernetes.io/part-of: tetral
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: cleanup
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: tetral-postgres
      ports:
        - protocol: TCP
          port: 5432
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
