apiVersion: v1
kind: ServiceAccount
metadata:
  name: cleanup
  namespace: tetral-system
  labels:
    app.kubernetes.io/name: cleanup
    app.kubernetes.io/part-of: tetral
automountServiceAccountToken: false
