apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: tetral-system
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: tetral
    app.kubernetes.io/managed-by: kustomize
    tetral.ai/exposure: public
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: api
  ports:
    - name: http
      port: 8080
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: api-metrics
  namespace: tetral-system
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: tetral
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: api
  ports:
    - name: metrics
      port: 8081
      targetPort: metrics
