apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
  namespace: tetral-system
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: tetral
    app.kubernetes.io/managed-by: kustomize
automountServiceAccountToken: false
