apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway
  namespace: tetral-system
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/part-of: tetral
automountServiceAccountToken: false
