apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth
  namespace: tetral-system
  labels:
    app.kubernetes.io/name: auth
    app.kubernetes.io/component: auth
    app.kubernetes.io/part-of: tetral
    app.kubernetes.io/managed-by: kustomize
automountServiceAccountToken: false
