apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-connector
  namespace: tetral-system
  labels:
    app.kubernetes.io/name: web-connector
    app.kubernetes.io/part-of: tetral
automountServiceAccountToken: false
