import { describe, expect, test } from "bun:test";
import { bytesFromHex, decryptAES256GCM, encryptAES256GCM, hexFromBytes } from "../../src/providers/crypto.js";
import {
  classifyProviderFailure,
  decryptPlatformProviderKeyRows,
  PlatformKeyPool,
  PlatformKeyPoolConstants,
  validatePlatformProviderKeyRows,
} from "../../src/providers/pool.js";
import type { EncryptedPlatformProviderKeyRow, GatewayCatalogProviderId, PlatformProviderKey, ProviderFailureAction } from "../../src/providers/pool.js";

const MasterKeyHex = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef";

describe("Gateway platform provider key crypto", () => {
  test("decrypts an aesgcm.go ciphertext fixture byte-for-byte", async () => {
    // Generated by the Go AES-256-GCM encryptor with MasterKeyHex.
    const goCiphertextHex = "e448216d240920a477e6e35f795742201df44e9614c12c78d8f8e40a78cfef9c26ff77cf5b9013dbe4";
    const plaintext = await decryptAES256GCM(bytesFromHex(goCiphertextHex), MasterKeyHex);

    expect(new TextDecoder().decode(plaintext)).toBe("sk-go-fixture");
  });

  test("encrypts with the aesgcm.go nonce-prefix framing used by the ops CLI path", async () => {
    const ciphertext = await encryptAES256GCM(new TextEncoder().encode("sk-platform-test"), MasterKeyHex, () => new Uint8Array(12).fill(7));
    const plaintext = await decryptAES256GCM(ciphertext, MasterKeyHex);

    expect(ciphertext.byteLength).toBe(12 + "sk-platform-test".length + 16);
    expect(hexFromBytes(ciphertext.slice(0, 12))).toBe("070707070707070707070707");
    expect(new TextDecoder().decode(plaintext)).toBe("sk-platform-test");
  });
});

describe("Gateway platform key pool", () => {
  test("T-POOL-6 validates active platform keys share one cache scope per provider", async () => {
    const rows = await Promise.all([
      encryptedRow("pfk_anthropic_a", "anthropic", "scope_a", "sk-a"),
      encryptedRow("pfk_anthropic_b", "anthropic", "scope_b", "sk-b"),
    ]);

    expect(() => validatePlatformProviderKeyRows(rows)).toThrow("cache_scope");
    await expect(decryptPlatformProviderKeyRows([rows[0]!], MasterKeyHex)).resolves.toEqual([
      {
        keyId: "pfk_anthropic_a",
        providerId: "anthropic",
        key: "sk-a",
        weight: 1,
        priority: 0,
        cacheScope: "scope_a",
      },
    ]);
  });

  test("T-POOL-7 selects the highest-priority tier and gives weight-zero keys floor traffic", () => {
    const pool = new PlatformKeyPool([
      key("pfk_low_weight", "anthropic", 0, 0),
      key("pfk_heavy", "anthropic", 90, 0),
      key("pfk_reserve", "anthropic", 10, 1),
    ], { random: () => 0.01 });

    const selection = pool.select("anthropic");

    expect(selection.ok).toBe(true);
    if (selection.ok) {
      expect(selection.key.keyId).toBe("pfk_low_weight");
    }
  });

  test("T-POOL-2/T-POOL-5/T-POOL-8 cools a rate-limited key, serves another key, and clamps cooldown", () => {
    let now = 1_000;
    const pool = new PlatformKeyPool([
      key("pfk_a", "anthropic", 1, 0),
      key("pfk_b", "anthropic", 1, 0),
    ], { now: () => now, random: () => 0 });

    const rateLimit = classifyProviderFailure("anthropic", {
      statusCode: 429,
      body: { error: { type: "rate_limit_error" } },
      headers: { "retry-after": "300" },
    });
    pool.recordFailure("pfk_a", rateLimit);

    expect(rateLimit).toMatchObject({
      action: "cooling",
      cooldownMs: PlatformKeyPoolConstants.cooldownCapMs,
      providerError: { code: "provider_rate_limited", retryable: true, retryAfterMs: PlatformKeyPoolConstants.cooldownCapMs },
    });
    expect(pool.select("anthropic")).toMatchObject({ ok: true, key: { keyId: "pfk_b" } });

    pool.recordFailure("pfk_b", rateLimit);
    expect(pool.select("anthropic")).toMatchObject({
      ok: false,
      error: { code: "platform_keys_exhausted", retryable: true, retryAfterMs: PlatformKeyPoolConstants.cooldownCapMs },
    });

    now += PlatformKeyPoolConstants.cooldownCapMs + 1;
    expect(pool.select("anthropic")).toMatchObject({ ok: true, key: { keyId: "pfk_a" } });
  });

  test("T-POOL-3 quarantines dead keys for the process lifetime and emits a structured alert hook", () => {
    const quarantineEvents: unknown[] = [];
    const pool = new PlatformKeyPool([key("pfk_dead", "anthropic", 1, 0)], { onQuarantine: (event) => quarantineEvents.push(event) });

    const deadKey = classifyProviderFailure("anthropic", { statusCode: 401, body: { error: { type: "authentication_error" } } });
    pool.recordFailure("pfk_dead", deadKey);
    pool.recordFailure("pfk_dead", deadKey);

    expect(deadKey).toMatchObject({ action: "quarantine", providerError: { retryable: false } });
    expect(quarantineEvents).toEqual([
      {
        keyId: "pfk_dead",
        providerId: "anthropic",
        providerError: deadKey.providerError,
      },
    ]);
    expect(pool.isQuarantined("pfk_dead")).toBe(true);
    expect(pool.select("anthropic")).toMatchObject({ ok: false, error: { code: "platform_keys_exhausted" } });
  });

  test("T-POOL-1 classifies provider body errors for all catalog providers", () => {
    const cases: Array<{
      name: string;
      providerId: GatewayCatalogProviderId;
      statusCode: number;
      body: unknown;
      wantAction: ProviderFailureAction;
    }> = [
      { name: "anthropic rate", providerId: "anthropic", statusCode: 429, body: { error: { type: "rate_limit_error" } }, wantAction: "cooling" },
      { name: "anthropic auth", providerId: "anthropic", statusCode: 401, body: {}, wantAction: "quarantine" },
      { name: "anthropic billing", providerId: "anthropic", statusCode: 402, body: { error: { type: "billing_error" } }, wantAction: "quarantine" },
      { name: "openai rate", providerId: "openai", statusCode: 429, body: { error: { code: "rate_limit_exceeded" } }, wantAction: "cooling" },
      { name: "openai auth", providerId: "openai", statusCode: 401, body: { error: { code: "invalid_api_key" } }, wantAction: "quarantine" },
      { name: "openai quota", providerId: "openai", statusCode: 429, body: { error: { code: "insufficient_quota" } }, wantAction: "quarantine" },
      { name: "openai usage not included", providerId: "openai", statusCode: 403, body: { error: { code: "usage_not_included" } }, wantAction: "quarantine" },
      { name: "openai invalid prompt", providerId: "openai", statusCode: 400, body: { error: { code: "invalid_prompt" } }, wantAction: "fail-fast" },
      { name: "openai server overloaded", providerId: "openai", statusCode: 400, body: { error: { code: "server_is_overloaded" } }, wantAction: "retryable" },
      { name: "deepseek rate", providerId: "deepseek", statusCode: 429, body: {}, wantAction: "cooling" },
      { name: "deepseek auth", providerId: "deepseek", statusCode: 401, body: {}, wantAction: "quarantine" },
      { name: "deepseek balance", providerId: "deepseek", statusCode: 402, body: { message: "Insufficient Balance" }, wantAction: "quarantine" },
      { name: "moonshot rate", providerId: "moonshotai", statusCode: 429, body: { error: { type: "rate_limit_reached_error" } }, wantAction: "cooling" },
      { name: "moonshot auth", providerId: "moonshotai", statusCode: 401, body: { error: { type: "invalid_authentication_error" } }, wantAction: "quarantine" },
      { name: "moonshot quota", providerId: "moonshotai", statusCode: 429, body: { error: { type: "exceeded_current_quota_error" } }, wantAction: "quarantine" },
      { name: "moonshot legacy balance", providerId: "moonshotai", statusCode: 403, body: { message: "balance is not enough" }, wantAction: "quarantine" },
      { name: "zai rate", providerId: "zai", statusCode: 429, body: { error: { code: 1308, message: "retry in 7 seconds" } }, wantAction: "cooling" },
      { name: "zai auth", providerId: "zai", statusCode: 401, body: { error: { code: 1001 } }, wantAction: "quarantine" },
      { name: "zai quota", providerId: "zai", statusCode: 429, body: { error: { code: 1113 } }, wantAction: "quarantine" },
    ];

    for (const testCase of cases) {
      expect(classifyProviderFailure(testCase.providerId, {
        statusCode: testCase.statusCode,
        body: testCase.body,
      }).action, testCase.name).toBe(testCase.wantAction);
    }
  });

  test("classifies the verified Anthropic credit exhaustion before generic 400 request shape", () => {
    const billingBody = {
      type: "error",
      error: {
        type: "invalid_request_error",
        message: "Your credit balance is too low to access the Anthropic API. Please go to Plans & Billing to upgrade or purchase credits.",
      },
    };

    expect(classifyProviderFailure("anthropic", { statusCode: 400, body: billingBody })).toMatchObject({
      action: "quarantine",
      providerError: {
        code: "provider_key_unavailable",
        message: "Provider key is not usable.",
        retryable: false,
        fatal: true,
        statusCode: 400,
      },
    });
    expect(classifyProviderFailure("anthropic", {
      statusCode: 400,
      body: { type: "error", error: { type: "invalid_request_error", message: "messages: Input should be valid." } },
    })).toMatchObject({
      action: "fail-fast",
      providerError: { code: "provider_request_invalid", retryable: false, fatal: true, statusCode: 400 },
    });
  });

  test("classifies a status-less untagged provider failure as retryable stream transport", () => {
    expect(classifyProviderFailure("anthropic", {})).toMatchObject({
      action: "retryable",
      providerError: {
        code: "provider_stream_error",
        retryable: true,
        fatal: false,
      },
    });
  });

  test("distinguishes the captured status-less DeepSeek balance signal from Moonshot body text", () => {
    expect(classifyProviderFailure("deepseek", {
      body: { message: "Insufficient Balance" },
      networkError: true,
    })).toMatchObject({
      action: "quarantine",
      semanticSignal: "deepseek_insufficient_balance",
      providerError: {
        code: "provider_key_unavailable",
        retryable: false,
        fatal: true,
      },
    });
    expect(classifyProviderFailure("moonshotai", {
      body: { message: "balance is not enough" },
      networkError: true,
    })).toMatchObject({
      action: "retryable",
      providerError: {
        code: "provider_stream_error",
        retryable: true,
        fatal: false,
      },
    });
    expect(classifyProviderFailure("deepseek", {
      body: { message: "prefix Insufficient Balance" },
      networkError: true,
    })).toMatchObject({
      action: "retryable",
      providerError: { code: "provider_stream_error" },
    });
  });

  test("normalizes every opaque status-less provider body without throwing or exposing it", () => {
    const cyclic: { self?: unknown; canary: string } = { canary: "cyclic-provider-body-canary" };
    cyclic.self = cyclic;
    const bodies: readonly unknown[] = [
      undefined,
      null,
      false,
      42,
      { opaque: "object-provider-body-canary" },
      "{malformed-provider-body-canary",
      cyclic,
    ];

    for (const body of bodies) {
      const classified = classifyProviderFailure("deepseek", { body, networkError: true });
      expect(classified).toMatchObject({
        action: "retryable",
        providerError: {
          code: "provider_stream_error",
          message: "Provider request failed.",
          retryable: true,
          fatal: false,
        },
      });
      expect(JSON.stringify(classified)).not.toMatch(/provider-body-canary/i);
    }
  });

  test("T-POOL-1 applies fallback rate-limit detection for plaintext and JSON bodies", () => {
    expect(classifyProviderFailure("openai", {
      statusCode: 429,
      body: { error: { message: "Rate limit reached for requests. Please try again later." } },
      headers: { "retry-after": "2" },
    })).toMatchObject({
      action: "cooling",
      cooldownMs: 2_000,
      providerError: {
        code: "provider_rate_limited",
        retryable: true,
        retryAfterMs: 2_000,
      },
    });

    expect(classifyProviderFailure("anthropic", {
      statusCode: 403,
      body: "Too many requests; retry after 7 seconds",
    })).toMatchObject({
      action: "cooling",
      cooldownMs: 7_000,
      providerError: {
        code: "provider_rate_limited",
        retryable: true,
        retryAfterMs: 7_000,
      },
    });
  });

  test("parses complete OpenAI reset durations and rejects trailing garbage", () => {
    const cases = [
      { name: "compound duration", value: "1m2s", wantCooldownMs: PlatformKeyPoolConstants.cooldownCapMs },
      { name: "compound duration with milliseconds", value: "1s250ms", wantCooldownMs: 1_250 },
      { name: "raw milliseconds", value: "1500", wantCooldownMs: 1_500 },
      { name: "trailing garbage", value: "1s250ms later", wantCooldownMs: PlatformKeyPoolConstants.defaultCooldownMs },
    ];

    for (const testCase of cases) {
      expect(classifyProviderFailure("openai", {
        statusCode: 429,
        body: { error: { code: "rate_limit_exceeded" } },
        headers: { "x-ratelimit-reset-requests": testCase.value },
      }), testCase.name).toMatchObject({
        action: "cooling",
        cooldownMs: testCase.wantCooldownMs,
        providerError: { retryAfterMs: testCase.wantCooldownMs },
      });
    }
  });

  test("keeps retry-after precedence in fallback rate-limit classification", () => {
    expect(classifyProviderFailure("openai", {
      statusCode: 429,
      body: { error: { message: "Rate limit reached. Please try again later." } },
      headers: {
        "retry-after": "2.5",
        "x-ratelimit-reset-requests": "1m2s",
      },
    })).toMatchObject({
      action: "cooling",
      cooldownMs: 2_500,
      providerError: { retryAfterMs: 2_500 },
    });
  });

  test("global request-shape failures fail fast while 5xx and timeouts stay retryable without quarantine", () => {
    expect(classifyProviderFailure("anthropic", { statusCode: 413, body: {} })).toMatchObject({
      action: "fail-fast",
      providerError: {
        code: "context_overflow",
        retryable: false,
        fatal: true,
      },
    });
    expect(classifyProviderFailure("openai", { statusCode: 400, body: { error: { code: "context_length_exceeded" } } })).toMatchObject({
      action: "fail-fast",
      providerError: {
        code: "context_overflow",
        retryable: false,
      },
    });
    expect(classifyProviderFailure("deepseek", { statusCode: 400, body: { message: "prompt is too long for the maximum context" } })).toMatchObject({
      action: "fail-fast",
      providerError: {
        code: "context_overflow",
        retryable: false,
      },
    });
    expect(classifyProviderFailure("openai", { statusCode: 404, body: {} })).toMatchObject({
      action: "retryable",
      providerError: {
        code: "provider_stream_error",
        retryable: true,
      },
    });
    for (const providerId of ["deepseek", "zai"] as const) {
      expect(classifyProviderFailure(providerId, { statusCode: 404, body: {} }), providerId).toMatchObject({
        action: "retryable",
        providerError: {
          code: "provider_stream_error",
          retryable: true,
        },
      });
    }
    expect(classifyProviderFailure("openai", { statusCode: 400, body: { error: { code: "usage_not_included" } } })).toMatchObject({
      action: "quarantine",
      providerError: {
        code: "provider_plan_required",
        retryable: false,
        fatal: true,
      },
    });
    expect(classifyProviderFailure("openai", { statusCode: 400, body: { error: { code: "invalid_prompt" } } })).toMatchObject({
      action: "fail-fast",
      providerError: {
        code: "provider_request_invalid",
        retryable: false,
        fatal: true,
      },
    });
    expect(classifyProviderFailure("openai", { statusCode: 400, body: { error: { code: "server_error" } } })).toMatchObject({
      action: "retryable",
      providerError: {
        code: "provider_stream_error",
        retryable: true,
        fatal: false,
      },
    });
    expect(classifyProviderFailure("anthropic", { statusCode: 400, body: {} })).toMatchObject({
      action: "fail-fast",
      providerError: { retryable: false },
    });
    expect(classifyProviderFailure("anthropic", { statusCode: 422, body: {} })).toMatchObject({
      action: "fail-fast",
      providerError: { retryable: false },
    });
    expect(classifyProviderFailure("anthropic", { statusCode: 529, body: {} })).toMatchObject({
      action: "retryable",
      providerError: { retryable: true },
    });
    expect(classifyProviderFailure("anthropic", { timeout: true })).toMatchObject({
      action: "retryable",
      providerError: { retryable: true },
    });
  });
});

async function encryptedRow(
  keyId: string,
  providerId: EncryptedPlatformProviderKeyRow["providerId"],
  cacheScope: string,
  plaintext: string,
): Promise<EncryptedPlatformProviderKeyRow> {
  return {
    keyId,
    providerId,
    encryptedKey: await encryptAES256GCM(new TextEncoder().encode(plaintext), MasterKeyHex, () => new Uint8Array(12).fill(keyId.length)),
    weight: 1,
    priority: 0,
    cacheScope,
    status: "active",
    updatedAt: "2026-07-01T00:00:00Z",
  };
}

function key(keyId: string, providerId: PlatformProviderKey["providerId"], weight: number, priority: number): PlatformProviderKey {
  return {
    keyId,
    providerId,
    key: `sk-${keyId}`,
    weight,
    priority,
    cacheScope: `${providerId}-scope`,
  };
}
